import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col h-[100vh] bg-gray-500 w-full gap-6">
          {/* Header */}
          <section className="w-full flex flex-row gap-2 py-8 px-8 border-b border-b-gray-200">
            <p>Back</p>
            <p>Avatar</p>
            <p>Name</p>
            <p className="ml-auto">Settings</p>
          </section>

          {children}
        </main>
      </body>
    </html>
  );
}
